//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Student
{
	profileId: string;
	address: string;
	deleted: boolean;
	identityUserId: string;
	lastValidStatus: string;
}
declare enum ExamTypeEnum {
	FIRST = 1,
	SECOND = 2,
	THIRD = 3,
	RETRY = 4,
	FINAL = 5
}
declare enum AttendanceEnum {
	ATTENDED = 1,
	MISSED = 2,
	REASONED = 3
}
declare enum SchoolRolesEnum {
	ADMINISTRADOR = 1,
	TEACHER = 2,
	STUDENT = 3
}
declare enum StudentStatusEnum {
	ENROLLED = 1,
	ACTIVE = 2,
	INACTIVE = 3,
	ACHIEVED = 4
}
